#!/usr/bin/bash

while getopts ":s:c:" opt; do
  case ${opt} in
    s ) 
      serverName="-s ${OPTARG}"
      ;;
    c )
      countryName=${OPTARG}
      serverName="-s `/home/christopher/Scripts/nordvpn.recommended.byCountry $countryName`"
      ;;
    \? ) echo "Usage: cmd [-s] [-c]"
      ;;
  esac
done


if [ -z $serverName ]
then 
	serverName="-s `/home/christopher/Scripts/nordvpn.recommended.byCountry`"
fi

function changeState {
	state=$1
	echo -e '\033[K{ "date": "'$(date)'", "openPynLoop": { "serverName": "'$serverName'", "state": "'$state'" } }'
	echo -e "\r"

}

changeState "initialising"

function waitingForWeb {
  changeState "waitingForWeb"

  sudo openpyn -x
  sleep 3
  while [[ $state = "waitingForWeb" ]] ; do
    sleep 1
    (ping -c 1 www.google.com)  && changeState "startOpenPyn"
  done
}

function startOpenPyn {
  #serverName="-s `/home/christopher/Scripts/nordvpn.recommended.germany`"

  sudo openpyn $serverName --tcp --double -f -d
  changeState "openPynStarted"
}

percentRegex="[.0-9]+%"
numberRegex="[0-9]+"

 #echo $pingOutput
  
function checkingWebIsUp {
  changeState "checkingWebIsUp"
  while [ "$state" == "checkingWebIsUp" ] ; do
    sleep 1
    pingOutput=`ping -q -c 16 -w 24 www.google.com`
    pingExitCode=$?
    
    echo -e "\033[Kbefore regex: $pingOutput\r"
    packetLoss=`echo $pingOutput | grep -oEi $percentRegex`
    echo -e "\033[Kping packet loss: $packetLoss\r"

    if [ $pingExitCode -eq 2 ] || [ "$packetLoss" == '100%' ]; then
      echo  pingExitCode=$pingExitCode
      changeState "webIsDown"
    else
      changeState "checkingWebIsUp"
    fi
  done
}



#clean exit
function ctrl_c() {
    echo "CTRL+C pressed. Exiting VPN..."
    sudo openpyn -x
    exit 1
}
trap ctrl_c INT

while true; do
    waitingForWeb
    startOpenPyn

    last_attempt=$(date +%s)
    checkingWebIsUp

    current_time=$(date +%s)
    elapsed_time=$((current_time - last_attempt))

    # If reconnection was attempted within a short interval (e.g., 10 seconds)
    if [ "$elapsed_time" -lt 60 ]; then
        echo "Quick reconnection attempts detected. Falling back for 60 seconds."
        sleep 60
    fi

done

